refactor to support more flexible arg/option positioning

diff --git a/git-rename b/git-rename
--- a/git-rename
+++ b/git-rename
@@ -74,7 +74,7 @@ if  ! command -v git > /dev/null 2>&1 ||
 
 
 # Get the branch name or short revision hash.
-branchName=$(git symbolic-ref -q --short HEAD || \
+CURRENT_REF_NAME=$(git symbolic-ref -q --short HEAD || \
              git rev-parse --short HEAD 2>&1)
 
 # Parse flags and options
@@ -105,13 +105,41 @@ for i in "$@"; do
             echo "git-rename: Error: Unknown option '$1'"
             shift
             ;;
+        *)
+            if [ -n "$1" ]; then
+                if [ -n "$ARGUMENTS" ]; then
+                    ARGUMENTS="${ARGUMENTS}?${1}"
+                else
+                    ARGUMENTS="${1}"
+                fi
+            fi
+            shift
+            ;;
     esac
 done
 
 
-# Get the new branch name
-# We are assuming the first non-option argument is the desired name
-targetName="$1"
+# Grab the target name from the arguments list
+# Also ensures only one argument is passed
+ARGS_COUNT=0
+ORIGINAL_IFS="$IFS"
+IFS="?"
+for arg in $ARGUMENTS; do
+    ARGS_COUNT=$((ARGS_COUNT+1))
+    if [ "$ARGS_COUNT" -gt 1 ]; then
+        echo "cannot exceed maximum of one argument"
+        exit 1
+    fi
+
+    if [ -z "$TARGET_NAME" ]; then
+        TARGET_NAME="$arg"
+    fi
+done
+IFS="$ORIGINAL_IFS"
+
+if [ -z "$TARGET_NAME" ]; then
+    parse_error=1
+fi
 
 
 # Output variable information if dry run
@@ -119,8 +147,8 @@ if [ $DRY_RUN -eq 1 ]; then
     echo "git-rename: Dry-run: Info: UPDATE_REMOTE: $UPDATE_REMOTE"
     echo "git-rename: Dry-run: Info: REMOTE_NAME: $REMOTE_NAME"
     echo "git-rename: Dry-run: Info: DRY_RUN: $DRY_RUN"
-    echo "git-rename: Dry-run: Info: branchName: $branchName"
-    echo "git-rename: Dry-run: Info: targetName: $targetName"
+    echo "git-rename: Dry-run: Info: CURRENT_REF_NAME: $CURRENT_REF_NAME"
+    echo "git-rename: Dry-run: Info: TARGET_NAME: $TARGET_NAME"
 fi
 
 
@@ -134,21 +162,21 @@ fi
 
 
 # Set commands to variables for easy re-use if dry running
-cmd_RenameBranch="git branch -m $targetName"
-cmd_PushBranch="git push --set-upstream $REMOTE_NAME $targetName"
-cmd_DeleteOldBranch="git push --delete $REMOTE_NAME $branchName"
+cmd_RenameBranch="git branch -m $TARGET_NAME"
+cmd_PushBranch="git push --set-upstream $REMOTE_NAME $TARGET_NAME"
+cmd_DeleteOldBranch="git push --delete $REMOTE_NAME $CURRENT_REF_NAME"
 
 
 # If dry run, print commands to stdout
 # Otherwise, execute the commands stored in variables
 if [ $DRY_RUN -eq 1 ]; then
-    echo "git-rename: Dry-run: Execute: $cmd_RenameBranch"
+    echo "git-rename: Dry-run: WillExecute: $cmd_RenameBranch"
 
     if [ $UPDATE_REMOTE -eq 1 ]; then
-        echo "git-rename: Dry-run: Execute: $cmd_PushBranch"
+        echo "git-rename: Dry-run: WillExecute: $cmd_PushBranch"
 
-        if [ "$targetName" != "$branchName" ]; then
-          echo "git-rename: Dry-run: Execute: $cmd_DeleteOldBranch"
+        if [ "$TARGET_NAME" != "$CURRENT_REF_NAME" ]; then
+          echo "git-rename: Dry-run: WillExecute: $cmd_DeleteOldBranch"
         fi
     fi
 else
@@ -156,7 +184,7 @@ else
 
     if [ $UPDATE_REMOTE -eq 1 ]; then
         if command "$cmd_PushBranch"; then
-            if [ "$targetName" != "$branchName" ]; then
+            if [ "$TARGET_NAME" != "$CURRENT_REF_NAME" ]; then
                 $cmd_DeleteOldBranch
             fi
         fi
